# Generated by Django 4.2.28 on 2026-02-09 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('odometer', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_personal_conveyance', models.BooleanField(default=False)),
                ('is_yard_move', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_logs', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_logs', to='trips.trip')),
            ],
            options={
                'db_table': 'duty_status_logs',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['driver', 'start_time'], name='duty_status_driver__5781b5_idx'), models.Index(fields=['driver', 'status'], name='duty_status_driver__ad4bae_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_miles', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('total_mileage', models.DecimalField(decimal_places=1, default=0, max_digits=9)),
                ('off_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sleeper_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipping_doc', models.CharField(blank=True, max_length=200)),
                ('shipper_commodity', models.CharField(blank=True, max_length=200)),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(blank=True, max_length=200)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_logs',
                'ordering': ['-date'],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
