# Generated by Django 4.2.28 on 2026-02-09 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('trip_plan', 'Trip Plan Generated'), ('pdf_generated', 'RODS PDF Generated'), ('hos_validation', 'HOS Validation Run'), ('hos_status', 'HOS Status Checked'), ('template_mapping_update', 'Template Mapping Updated')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('rules_triggered', models.JSONField(blank=True, default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='trips.trip')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', 'timestamp'], name='audit_logs_driver__a9c18c_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx')],
            },
        ),
    ]
