# Generated by Django 4.2.28 on 2026-02-09 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', models.CharField(max_length=200)),
                ('current_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_location', models.CharField(max_length=200)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('route_data', models.JSONField(blank=True, null=True)),
                ('total_distance_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('short_haul_exemption', models.BooleanField(default=False)),
                ('adverse_driving', models.BooleanField(default=False)),
                ('sleeper_berth_split_first', models.IntegerField(blank=True, null=True)),
                ('sleeper_berth_split_second', models.IntegerField(blank=True, null=True)),
                ('total_trip_days', models.IntegerField(blank=True, null=True)),
                ('total_driving_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('rest', 'Rest Stop (10hr)'), ('fuel', 'Fuel Stop'), ('break', '30-Min Break')], max_length=20)),
                ('location_name', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.IntegerField()),
                ('duration_minutes', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_stops',
                'ordering': ['sequence'],
            },
        ),
    ]
